site_name: Ausi BLog
site_url: https://blog.ausiplayz.lol
site_description: A blog about programming, technology and more.
site_author: Noah
copyright: Copyright &copy; 2024 AusiPlayz

repo_name: Blog
repo_url: https://github.com/AustrianNoah/BlogSite/
edit_uri: https://github.com/AustrianNoah/BlogSite/edit/main/docs

plugins:
  - blog

theme:
  name: material
  features:
    - toc.integrate
    - content.code.annotate
    - content.code.copy
    - navigation.tabs
  palette:
    - scheme: slate
      primary: black
      accent: blue-grey

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  generator: false

nav:
  - Home:
      - index.md
      - Guides:
        - Setup static IP with OpenVPN: guides/setup-static-ip-with-openvpn.md
  - News: blog/index.md
